version: "3.8"

services:
  location-annotator:
    image: docker.synapse.org/syn28137039/location-annotator-mvp:0.1
    build:
      context: server
      dockerfile: Dockerfile
    container_name: location-annotator
    networks:
      - nlpsandbox-internal

  nginx:
    image: nginx:1.19.6-alpine
    container_name: location-annotator-nginx
    restart: always
    environment:
      - TOOL_HOST=location-annotator
      - TOOL_PORT=8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates:ro
    networks:
      - nlpsandbox
      - nlpsandbox-internal
    ports:
      - "80:80"
    depends_on:
      - location-annotator

networks:
  nlpsandbox:
  nlpsandbox-internal:
    internal: true